version: '3.7'

services: 
  api:
    build: 
      context: ../../dockerfiles/node-api
    ports: 
      - 3000:3000
  web:
    image: nginx
    volumes: 
      - ./html:/usr/share/nginx/html
    ports: 
      - 80:80